/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.FuncList.FuncList;
import org.example.FuncList.Func1;
import org.example.FuncList.Func2;
import java.util.function.*;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Func1 f1 = FuncList::isOdd;
        Func2 f2 = new FuncList()::passCheck;

        System.out.println(f1.call(15));
        System.out.println(f2.call(70, "Smith"));

        Func1 f3 = x -> x % 2 == 1;
        Func2 f4 = (point, name) -> name + " " + (point > 65 ? "OK" : "NG");

        System.out.println(f3.call(15));
        System.out.println(f4.call(70, "Smith"));

        IntPredicate p = x -> x % 2 == 1;
        System.out.println(p.test(15));

        List<String> names = new ArrayList<>();
        names.add("Smith");
        names.add("Tanaka");
        names.add("Suzuki");
        names.add("Yamamoto");

        names.stream().filter(name -> name.length() >= 7).forEach(name -> System.out.println(name));
    }
}
