/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            GetGithubUser.main(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
