/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Launcher.*;;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Launcher.main(args);
        MemoryEater.main(args);
    }
}
