/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("show list of items over 1 yes");
        ArrayList<Item> items = ItemDAO.findByMinimumPrice(1);
        for (Item item : items) {
            System.out.println("name: " + item.name() + ", price: " + item.price() + ", weight: " + item.weight());
        }
    }
}
